import { useState, useRef, useMemo, useCallback, useEffect } from "react";
import {
  Clock,
  Smile,
  Cat,
  Coffee,
  Dumbbell,
  Car,
  Lightbulb,
  Hash,
  Flag,
  Search,
  X,
} from "lucide-react";
import { useClickOutside } from "../../hooks/useClickOutside";

interface EmojiPickerProps {
  onSelect: (emoji: string) => void;
  onClose: () => void;
  /** Where to position relative to anchor */
  position?: "top" | "bottom";
  /** Alignment */
  align?: "left" | "right";
  className?: string;
}

interface EmojiCategory {
  id: string;
  label: string;
  icon: React.ElementType;
  emojis: string[];
}

const CATEGORIES: EmojiCategory[] = [
  {
    id: "recent",
    label: "Recently Used",
    icon: Clock,
    emojis: [], // populated dynamically
  },
  {
    id: "smileys",
    label: "Smileys & People",
    icon: Smile,
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "🙃",
      "😉",
      "😊",
      "😇",
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "😚",
      "😙",
      "🥲",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      "🤑",
      "🤗",
      "🤭",
      "🫢",
      "🫣",
      "🤫",
      "🤔",
      "🫡",
      "🤐",
      "🤨",
      "😐",
      "😑",
      "😶",
      "🫥",
      "😏",
      "😒",
      "🙄",
      "😬",
      "🤥",
      "😌",
      "😔",
      "😪",
      "🤤",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🥵",
      "🥶",
      "🥴",
      "😵",
      "🤯",
      "🤠",
      "🥳",
      "🥸",
      "😎",
      "🤓",
      "🧐",
      "😕",
      "🫤",
      "😟",
      "🙁",
      "😮",
      "😯",
      "😲",
      "😳",
      "🥺",
      "🥹",
      "😦",
      "😧",
      "😨",
      "😰",
      "😥",
      "😢",
      "😭",
      "😱",
      "😖",
      "😣",
      "😞",
      "😓",
      "😩",
      "😫",
      "🥱",
      "😤",
      "😡",
      "😠",
      "🤬",
      "😈",
      "👿",
      "💀",
      "☠️",
      "💩",
      "🤡",
      "👹",
      "👺",
      "👻",
      "👽",
      "👾",
      "🤖",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
      "🙈",
      "🙉",
      "🙊",
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "🫱",
      "🫲",
      "🫳",
      "🫴",
      "🫷",
      "🫸",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🫰",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "🫵",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "🫶",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "💪",
      "🦾",
    ],
  },
  {
    id: "animals",
    label: "Animals & Nature",
    icon: Cat,
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐻‍❄️",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🙈",
      "🙉",
      "🙊",
      "🐒",
      "🐔",
      "🐧",
      "🐦",
      "🐤",
      "🐣",
      "🐥",
      "🦆",
      "🦅",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🐝",
      "🪱",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🌸",
      "🌹",
      "🌺",
      "🌻",
      "🌼",
      "🌷",
      "🌱",
      "🌿",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🪻",
      "🪷",
      "🌵",
      "🌴",
      "🌲",
      "🎋",
      "🎍",
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: Coffee,
    emojis: [
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🥑",
      "🍆",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🫘",
      "🍞",
      "🥐",
      "🥖",
      "🫓",
      "🥨",
      "🥯",
      "🧇",
      "🥞",
      "🧈",
      "🍳",
      "🥚",
      "🍕",
      "🌭",
      "🍔",
      "🍟",
      "🌮",
      "🌯",
      "🫔",
      "🥙",
      "🧆",
      "🍝",
      "🍜",
      "🍲",
      "🍛",
      "🍣",
      "🍱",
      "🥟",
      "🍤",
      "🍙",
      "🍚",
      "🎂",
      "🍰",
      "🧁",
      "🥧",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🍯",
      "☕",
      "🍵",
      "🧃",
      "🥤",
      "🍶",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🍸",
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: Dumbbell,
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🏓",
      "🏸",
      "🏒",
      "🥊",
      "🥋",
      "🎯",
      "⛳",
      "🏹",
      "🎣",
      "🤿",
      "🥅",
      "⛸️",
      "🎿",
      "🛷",
      "🎮",
      "🕹️",
      "🎲",
      "🧩",
      "♟️",
      "🎭",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎹",
      "🥁",
      "🎷",
      "🎺",
      "🎸",
      "🪕",
      "🎻",
      "🎪",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🏅",
      "🎖️",
      "🎗️",
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: Car,
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🏍️",
      "🛵",
      "🚲",
      "🛴",
      "🚔",
      "🚍",
      "✈️",
      "🛩️",
      "🛫",
      "🛬",
      "🚀",
      "🛸",
      "🚁",
      "🛶",
      "⛵",
      "🚤",
      "🏠",
      "🏡",
      "🏢",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏩",
      "🏪",
      "🏫",
      "🏬",
      "🏭",
      "🗼",
      "🗽",
      "⛪",
      "🕌",
      "🕍",
      "⛩️",
      "🕋",
      "🌍",
      "🌎",
      "🌏",
      "🗺️",
      "🧭",
      "🏔️",
      "⛰️",
      "🌋",
      "🗻",
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: Lightbulb,
    emojis: [
      "⌚",
      "📱",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "💾",
      "💿",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "🧭",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "💡",
      "🔦",
      "🕯️",
      "🪔",
      "🧯",
      "💰",
      "💴",
      "💵",
      "💶",
      "💷",
      "💎",
      "⚖️",
      "🪜",
      "🧰",
      "🪛",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🔩",
      "⚙️",
      "🧱",
      "📎",
      "🖇️",
      "✂️",
      "📐",
      "📏",
      "🔑",
      "🗝️",
      "🔒",
      "🔓",
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💝",
      "💘",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉️",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: Hash,
    emojis: [
      "🏧",
      "🚮",
      "🚰",
      "♿",
      "🚹",
      "🚺",
      "🚻",
      "🚼",
      "🚾",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "⚠️",
      "🚸",
      "⛔",
      "🚫",
      "🚳",
      "🚭",
      "🚯",
      "🚱",
      "🚷",
      "📵",
      "🔞",
      "☢️",
      "☣️",
      "⬆️",
      "↗️",
      "➡️",
      "↘️",
      "⬇️",
      "↙️",
      "⬅️",
      "↖️",
      "↕️",
      "↔️",
      "↩️",
      "↪️",
      "⤴️",
      "⤵️",
      "🔃",
      "🔄",
      "🔙",
      "🔚",
      "🔛",
      "🔜",
      "🔝",
      "✅",
      "❌",
      "❎",
      "➕",
      "➖",
      "➗",
      "✖️",
      "♾️",
      "❓",
      "❔",
      "❕",
      "❗",
      "〰️",
      "💲",
      "⚕️",
      "♻️",
      "⚜️",
      "🔱",
      "📛",
      "🔰",
      "⭕",
      "✳️",
      "❇️",
      "©️",
      "®️",
      "™️",
      "#️⃣",
      "*️⃣",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
      "🔠",
      "🔡",
      "🔢",
      "🔣",
      "🔤",
      "🅰️",
      "🆎",
      "🅱️",
      "🆑",
      "🆒",
      "🆓",
      "ℹ️",
      "🆔",
      "Ⓜ️",
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: Flag,
    emojis: [
      "🏁",
      "🚩",
      "🎌",
      "🏴",
      "🏳️",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
      "🇮🇹",
      "🇺🇸",
      "🇬🇧",
      "🇫🇷",
      "🇩🇪",
      "🇪🇸",
      "🇵🇹",
      "🇧🇷",
      "🇯🇵",
      "🇰🇷",
      "🇨🇳",
      "🇮🇳",
      "🇷🇺",
      "🇦🇺",
      "🇨🇦",
      "🇲🇽",
      "🇦🇷",
      "🇨🇱",
      "🇨🇴",
      "🇵🇪",
      "🇻🇪",
      "🇪🇨",
      "🇧🇴",
      "🇺🇾",
      "🇵🇾",
      "🇹🇷",
      "🇸🇦",
      "🇦🇪",
      "🇪🇬",
      "🇿🇦",
      "🇳🇬",
      "🇰🇪",
      "🇬🇭",
      "🇪🇹",
      "🇲🇦",
      "🇹🇳",
      "🇩🇿",
      "🇮🇱",
      "🇵🇸",
      "🇱🇧",
      "🇯🇴",
      "🇮🇶",
      "🇮🇷",
      "🇵🇰",
      "🇧🇩",
      "🇱🇰",
      "🇳🇵",
      "🇹🇭",
      "🇻🇳",
      "🇮🇩",
      "🇲🇾",
      "🇵🇭",
      "🇸🇬",
      "🇭🇰",
      "🇹🇼",
      "🇳🇿",
      "🇫🇮",
      "🇸🇪",
      "🇳🇴",
      "🇩🇰",
      "🇮🇸",
      "🇳🇱",
      "🇧🇪",
      "🇨🇭",
      "🇦🇹",
      "🇵🇱",
      "🇨🇿",
      "🇭🇺",
      "🇷🇴",
      "🇧🇬",
      "🇭🇷",
      "🇷🇸",
      "🇺🇦",
      "🇬🇷",
      "🇮🇪",
      "🇪🇺",
    ],
  },
];

const RECENT_STORAGE_KEY = "emoji-recent";
const MAX_RECENT = 24;

function getRecent(): string[] {
  try {
    return JSON.parse(localStorage.getItem(RECENT_STORAGE_KEY) || "[]");
  } catch {
    return [];
  }
}

function saveRecent(emoji: string) {
  const prev = getRecent().filter((e) => e !== emoji);
  const next = [emoji, ...prev].slice(0, MAX_RECENT);
  localStorage.setItem(RECENT_STORAGE_KEY, JSON.stringify(next));
}

/** Emoji → searchable English keywords */
const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "grinning face happy smile",
  "😃": "smiley face happy open mouth",
  "😄": "smile face happy grin eyes",
  "😁": "beaming face grin teeth",
  "😆": "laughing face squinting happy",
  "😅": "sweat smile nervous grin",
  "🤣": "rolling laughing rofl lmao floor",
  "😂": "joy tears laughing crying happy",
  "🙂": "slightly smiling face",
  "🙃": "upside down face silly",
  "😉": "wink winking face",
  "😊": "blush smiling happy shy",
  "😇": "angel halo innocent",
  "🥰": "love hearts face smiling",
  "😍": "heart eyes love face",
  "🤩": "star struck eyes excited",
  "😘": "kiss blowing face love",
  "😗": "kissing face",
  "😚": "kissing closed eyes face",
  "😙": "kissing smiling eyes face",
  "🥲": "smiling tear sad happy",
  "😋": "yummy delicious tongue food",
  "😛": "tongue out face",
  "😜": "wink tongue crazy zany",
  "🤪": "zany crazy wild face",
  "😝": "squinting tongue face",
  "🤑": "money mouth dollar rich",
  "🤗": "hug hugging face open arms",
  "🤭": "shy giggle hand over mouth",
  "🫢": "surprised hand over mouth",
  "🫣": "peeking eye face",
  "🤫": "shush quiet secret silence",
  "🤔": "thinking hmm face wonder",
  "🫡": "salute saluting face",
  "🤐": "zipper mouth shut quiet",
  "🤨": "raised eyebrow suspicious",
  "😐": "neutral face expressionless",
  "😑": "expressionless face flat",
  "😶": "no mouth silent face",
  "🫥": "dotted line face invisible",
  "😏": "smirk smirking face sly",
  "😒": "unamused face annoyed",
  "🙄": "eye roll face annoyed",
  "😬": "grimace awkward nervous",
  "🤥": "lying pinocchio nose",
  "😌": "relieved face peaceful calm",
  "😔": "pensive face sad thoughtful",
  "😪": "sleepy face tired drool",
  "🤤": "drooling face hungry",
  "😴": "sleeping face zzz",
  "😷": "mask sick medical face",
  "🤒": "thermometer sick fever ill",
  "🤕": "bandage hurt injured head",
  "🤢": "nauseated sick green face",
  "🤮": "vomiting throwing up sick",
  "🥵": "hot face overheated sweating",
  "🥶": "cold face freezing frozen",
  "🥴": "woozy dizzy drunk face",
  "😵": "dizzy face knocked out",
  "🤯": "exploding head mind blown shock",
  "🤠": "cowboy hat face western",
  "🥳": "party face celebration birthday",
  "🥸": "disguise face glasses nose",
  "😎": "sunglasses cool face",
  "🤓": "nerd glasses face geek",
  "🧐": "monocle face curious inspect",
  "😕": "confused face puzzled",
  "🫤": "diagonal mouth face uncertain",
  "😟": "worried face concern",
  "🙁": "frowning face sad slightly",
  "😮": "open mouth face surprised",
  "😯": "hushed face surprised quiet",
  "😲": "astonished face shocked",
  "😳": "flushed face embarrassed",
  "🥺": "pleading face puppy eyes cute",
  "🥹": "holding back tears emotional",
  "😦": "frowning open mouth face",
  "😧": "anguished face distressed",
  "😨": "fearful face scared afraid",
  "😰": "anxious face sweat nervous",
  "😥": "sad relieved disappointed",
  "😢": "crying face tear sad",
  "😭": "sobbing loudly crying face",
  "😱": "screaming fear face scared",
  "😖": "confounded face frustrated",
  "😣": "persevering face struggling",
  "😞": "disappointed face sad down",
  "😓": "downcast face sweat sad",
  "😩": "weary face tired exhausted",
  "😫": "tired face exhausted fed up",
  "🥱": "yawning face bored sleepy",
  "😤": "huffing face angry steam",
  "😡": "angry pouting face mad red",
  "😠": "angry face mad annoyed",
  "🤬": "swearing cursing symbols angry",
  "😈": "devil smiling purple horns",
  "👿": "angry devil imp horns",
  "💀": "skull dead death skeleton",
  "☠️": "skull crossbones death danger",
  "💩": "poop poo pile",
  "🤡": "clown face circus",
  "👹": "ogre monster japanese",
  "👺": "goblin monster japanese",
  "👻": "ghost boo halloween spooky",
  "👽": "alien extraterrestrial ufo",
  "👾": "alien monster game space invader",
  "🤖": "robot face bot machine",
  "😺": "cat smile happy grinning",
  "😸": "cat grin happy face",
  "😹": "cat joy tears laughing",
  "😻": "cat heart eyes love",
  "😼": "cat smirk wry",
  "😽": "cat kiss face",
  "🙀": "cat weary shocked",
  "😿": "cat crying sad tear",
  "😾": "cat pouting angry",
  "🙈": "see no evil monkey eyes",
  "🙉": "hear no evil monkey ears",
  "🙊": "speak no evil monkey mouth",
  "👋": "wave hand hello bye greeting",
  "🤚": "raised back hand",
  "🖐️": "hand splayed fingers open",
  "✋": "raised hand stop high five",
  "🖖": "vulcan salute spock",
  "🫱": "rightward hand right",
  "🫲": "leftward hand left",
  "🫳": "palm down hand",
  "🫴": "palm up hand",
  "🫷": "leftward push",
  "🫸": "rightward push",
  "👌": "ok okay perfect hand",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small tiny little",
  "✌️": "peace victory hand sign",
  "🤞": "crossed fingers luck hope",
  "🫰": "hand index thumb crossed",
  "🤟": "love you hand gesture",
  "🤘": "rock on horns metal",
  "🤙": "call me hand phone shaka",
  "👈": "point left hand finger",
  "👉": "point right hand finger",
  "👆": "point up hand finger",
  "🖕": "middle finger",
  "👇": "point down hand finger",
  "☝️": "index point up finger",
  "🫵": "index pointing at viewer you",
  "👍": "thumbs up like good yes approve",
  "👎": "thumbs down dislike bad no",
  "✊": "raised fist power strong",
  "👊": "fist bump punch",
  "🤛": "left facing fist bump",
  "🤜": "right facing fist bump",
  "👏": "clapping hands applause bravo",
  "🙌": "raising hands celebration hooray",
  "🫶": "heart hands love gesture",
  "👐": "open hands palms",
  "🤲": "palms up together receive",
  "🤝": "handshake deal agreement",
  "🙏": "pray please thank you folded hands",
  "💪": "muscle strong bicep flexed arm",
  "🦾": "mechanical arm prosthetic robot",
  "🐶": "dog face puppy pet",
  "🐱": "cat face kitten pet",
  "🐭": "mouse face rat",
  "🐹": "hamster face pet",
  "🐰": "rabbit bunny face",
  "🦊": "fox face",
  "🐻": "bear face",
  "🐼": "panda face bear",
  "🐻‍❄️": "polar bear arctic",
  "🐨": "koala face australia",
  "🐯": "tiger face cat",
  "🦁": "lion face king",
  "🐮": "cow face",
  "🐷": "pig face",
  "🐸": "frog face",
  "🐵": "monkey face",
  "🐒": "monkey animal",
  "🐔": "chicken hen bird",
  "🐧": "penguin bird arctic",
  "🐦": "bird",
  "🐤": "baby chick bird",
  "🐣": "hatching chick bird egg",
  "🐥": "front facing baby chick bird",
  "🦆": "duck bird",
  "🦅": "eagle bird",
  "🦉": "owl bird night wise",
  "🦇": "bat animal night vampire",
  "🐺": "wolf face",
  "🐗": "boar pig wild",
  "🐴": "horse face",
  "🦄": "unicorn face magical",
  "🐝": "bee honeybee bug insect",
  "🪱": "worm bug",
  "🐛": "bug insect caterpillar",
  "🦋": "butterfly insect beautiful",
  "🐌": "snail slow shell",
  "🐞": "ladybug insect bug",
  "🌸": "cherry blossom flower pink spring",
  "🌹": "rose flower red love",
  "🌺": "hibiscus flower tropical",
  "🌻": "sunflower flower yellow sun",
  "🌼": "blossom flower",
  "🌷": "tulip flower spring",
  "🌱": "seedling plant sprout grow",
  "🌿": "herb plant leaf green",
  "🍀": "four leaf clover luck lucky",
  "🍁": "maple leaf fall autumn canada",
  "🍂": "fallen leaf autumn fall",
  "🍃": "leaf fluttering wind",
  "🪻": "hyacinth flower purple",
  "🪷": "lotus flower zen",
  "🌵": "cactus desert plant",
  "🌴": "palm tree tropical island",
  "🌲": "evergreen tree pine christmas",
  "🎋": "tanabata tree bamboo",
  "🎍": "pine decoration japanese",
  "🍎": "red apple fruit",
  "🍐": "pear fruit green",
  "🍊": "orange tangerine mandarin fruit",
  "🍋": "lemon citrus yellow fruit",
  "🍌": "banana fruit yellow",
  "🍉": "watermelon fruit summer",
  "🍇": "grapes fruit purple",
  "🍓": "strawberry fruit red berry",
  "🫐": "blueberry fruit berry blue",
  "🍒": "cherry fruit red",
  "🍑": "peach fruit",
  "🥭": "mango fruit tropical",
  "🍍": "pineapple fruit tropical",
  "🥥": "coconut tropical",
  "🥝": "kiwi fruit green",
  "🍅": "tomato vegetable red",
  "🥑": "avocado fruit green",
  "🍆": "eggplant aubergine purple vegetable",
  "🥦": "broccoli vegetable green",
  "🥬": "leafy green vegetable lettuce",
  "🥒": "cucumber pickle vegetable green",
  "🌶️": "hot pepper chili spicy",
  "🫑": "bell pepper vegetable",
  "🌽": "corn ear maize",
  "🥕": "carrot vegetable orange",
  "🧄": "garlic clove",
  "🧅": "onion vegetable",
  "🥔": "potato vegetable",
  "🍠": "sweet potato roasted",
  "🫘": "beans legume",
  "🍞": "bread loaf",
  "🥐": "croissant pastry french",
  "🥖": "baguette bread french",
  "🫓": "flatbread naan pita",
  "🥨": "pretzel bread snack",
  "🥯": "bagel bread breakfast",
  "🧇": "waffle breakfast",
  "🥞": "pancakes breakfast stack",
  "🧈": "butter dairy",
  "🍳": "cooking egg fried breakfast",
  "🥚": "egg food",
  "🍕": "pizza slice food italian",
  "🌭": "hot dog food",
  "🍔": "hamburger burger cheeseburger food",
  "🍟": "french fries food chips",
  "🌮": "taco mexican food",
  "🌯": "burrito wrap mexican food",
  "🫔": "tamale mexican food",
  "🥙": "pita falafel food",
  "🧆": "falafel food",
  "🍝": "spaghetti pasta italian food",
  "🍜": "noodle soup ramen food",
  "🍲": "pot stew food",
  "🍛": "curry rice food",
  "🍣": "sushi japanese food",
  "🍱": "bento box japanese food",
  "🥟": "dumpling food",
  "🍤": "shrimp prawn fried food",
  "🍙": "rice ball onigiri japanese",
  "🍚": "cooked rice food",
  "🎂": "birthday cake celebration party",
  "🍰": "cake slice shortcake dessert",
  "🧁": "cupcake muffin dessert sweet",
  "🥧": "pie dessert",
  "🍫": "chocolate bar candy sweet",
  "🍬": "candy sweet",
  "🍭": "lollipop candy sweet",
  "🍮": "custard pudding flan dessert",
  "🍯": "honey pot sweet",
  "☕": "coffee hot beverage cup tea",
  "🍵": "tea cup green beverage",
  "🧃": "juice box beverage",
  "🥤": "cup straw beverage soda",
  "🍶": "sake japanese beverage",
  "🍺": "beer mug drink",
  "🍻": "clinking beer mugs cheers",
  "🥂": "clinking glasses champagne cheers toast",
  "🍷": "wine glass red drink",
  "🍸": "cocktail martini drink",
  "⚽": "soccer football ball sport",
  "🏀": "basketball ball sport",
  "🏈": "american football ball sport",
  "⚾": "baseball ball sport",
  "🥎": "softball ball sport",
  "🎾": "tennis ball sport",
  "🏐": "volleyball ball sport",
  "🏉": "rugby ball sport",
  "🥏": "flying disc frisbee sport",
  "🎱": "pool billiards ball eight",
  "🏓": "ping pong table tennis sport",
  "🏸": "badminton racquet sport",
  "🏒": "hockey ice stick puck sport",
  "🥊": "boxing glove fight sport",
  "🥋": "martial arts karate judo",
  "🎯": "target bullseye dart",
  "⛳": "golf flag hole sport",
  "🏹": "bow arrow archery sport",
  "🎣": "fishing rod pole sport",
  "🤿": "diving mask snorkel swim",
  "🥅": "goal net sport",
  "⛸️": "ice skating figure sport",
  "🎿": "skiing snow sport winter",
  "🛷": "sled sledge toboggan winter",
  "🎮": "video game controller joystick",
  "🕹️": "joystick arcade game",
  "🎲": "dice game random chance",
  "🧩": "puzzle piece jigsaw",
  "♟️": "chess pawn board game",
  "🎭": "theater performing arts drama masks",
  "🎨": "art palette painting",
  "🎬": "clapper board movie film cinema",
  "🎤": "microphone singing karaoke",
  "🎧": "headphone headphones music audio",
  "🎼": "music score notes",
  "🎹": "piano musical keyboard",
  "🥁": "drum percussion music",
  "🎷": "saxophone jazz music",
  "🎺": "trumpet brass music",
  "🎸": "guitar music rock",
  "🪕": "banjo music string",
  "🎻": "violin fiddle music string",
  "🎪": "circus tent carnival",
  "🏆": "trophy winner champion award",
  "🥇": "gold medal first place winner",
  "🥈": "silver medal second place",
  "🥉": "bronze medal third place",
  "🏅": "sports medal award",
  "🎖️": "military medal honor",
  "🎗️": "ribbon awareness reminder",
  "🚗": "car automobile vehicle red",
  "🚕": "taxi cab yellow car",
  "🚙": "suv sport utility vehicle",
  "🚌": "bus public transport",
  "🚎": "trolleybus tram",
  "🏎️": "racing car formula speed",
  "🚓": "police car",
  "🚑": "ambulance emergency medical",
  "🚒": "fire engine truck",
  "🚐": "minibus van",
  "🛻": "pickup truck",
  "🚚": "delivery truck",
  "🚛": "articulated lorry truck",
  "🚜": "tractor farm",
  "🏍️": "motorcycle racing bike",
  "🛵": "motor scooter vespa",
  "🚲": "bicycle bike cycling",
  "🛴": "kick scooter",
  "🚔": "police car oncoming",
  "🚍": "bus oncoming",
  "✈️": "airplane plane flight travel",
  "🛩️": "small airplane plane",
  "🛫": "departure airplane takeoff",
  "🛬": "arrival airplane landing",
  "🚀": "rocket launch space",
  "🛸": "flying saucer ufo alien",
  "🚁": "helicopter chopper",
  "🛶": "canoe kayak boat paddle",
  "⛵": "sailboat boat sailing",
  "🚤": "speedboat motorboat boat",
  "🏠": "house home building",
  "🏡": "house garden home",
  "🏢": "office building city",
  "🏣": "japanese post office",
  "🏤": "post office european",
  "🏥": "hospital medical",
  "🏦": "bank money building",
  "🏨": "hotel travel building",
  "🏩": "love hotel building",
  "🏪": "convenience store shop",
  "🏫": "school education building",
  "🏬": "department store shopping",
  "🏭": "factory industry building",
  "🗼": "tokyo tower japan",
  "🗽": "statue liberty new york",
  "⛪": "church religion building",
  "🕌": "mosque islam religion",
  "🕍": "synagogue jewish religion",
  "⛩️": "shinto shrine torii japan",
  "🕋": "kaaba islam mecca",
  "🌍": "earth globe europe africa world",
  "🌎": "earth globe americas world",
  "🌏": "earth globe asia australia world",
  "🗺️": "world map atlas",
  "🧭": "compass navigation direction",
  "🏔️": "snow capped mountain",
  "⛰️": "mountain",
  "🌋": "volcano eruption lava",
  "🗻": "mount fuji japan",
  "⌚": "watch time wrist",
  "📱": "mobile phone smartphone cell",
  "💻": "laptop computer pc",
  "⌨️": "keyboard typing computer",
  "🖥️": "desktop computer monitor screen",
  "🖨️": "printer",
  "🖱️": "computer mouse click",
  "🖲️": "trackball mouse",
  "💾": "floppy disk save",
  "💿": "cd disc optical",
  "📷": "camera photo picture",
  "📸": "camera flash photo",
  "📹": "video camera camcorder",
  "🎥": "movie camera film cinema",
  "📽️": "film projector movie",
  "🎞️": "film frames movie",
  "📞": "telephone receiver phone call",
  "☎️": "telephone phone",
  "📟": "pager",
  "📠": "fax machine",
  "📺": "television tv screen",
  "📻": "radio",
  "🎙️": "studio microphone podcast",
  "🎚️": "level slider audio",
  "🎛️": "control knobs mixer",
  "⏱️": "stopwatch timer",
  "⏲️": "timer clock alarm",
  "⏰": "alarm clock wake up",
  "🕰️": "mantelpiece clock",
  "💡": "light bulb idea bright",
  "🔦": "flashlight torch",
  "🕯️": "candle flame light",
  "🪔": "diya lamp oil",
  "🧯": "fire extinguisher",
  "💰": "money bag dollar rich",
  "💴": "yen banknote money japan",
  "💵": "dollar banknote money usa",
  "💶": "euro banknote money europe",
  "💷": "pound banknote money uk",
  "💎": "gem diamond jewel precious",
  "⚖️": "balance scale justice law",
  "🪜": "ladder climb",
  "🧰": "toolbox repair fix",
  "🪛": "screwdriver tool fix",
  "🔧": "wrench spanner tool fix",
  "🔨": "hammer tool build",
  "⚒️": "hammer pick tool",
  "🛠️": "hammer wrench tool fix",
  "⛏️": "pick mining tool",
  "🔩": "nut bolt screw",
  "⚙️": "gear cog settings",
  "🧱": "brick wall build",
  "📎": "paperclip attachment file",
  "🖇️": "linked paperclips attachment",
  "✂️": "scissors cut",
  "📐": "triangular ruler measure",
  "📏": "straight ruler measure",
  "🔑": "key lock access password",
  "🗝️": "old key lock antique",
  "🔒": "locked padlock secure",
  "🔓": "unlocked padlock open",
  "❤️": "red heart love",
  "🧡": "orange heart love",
  "💛": "yellow heart love",
  "💚": "green heart love",
  "💙": "blue heart love",
  "💜": "purple heart love",
  "🖤": "black heart dark love",
  "🤍": "white heart love pure",
  "🤎": "brown heart love",
  "💔": "broken heart love sad",
  "❤️‍🔥": "heart fire burning love passion",
  "❣️": "heart exclamation love",
  "💕": "two hearts love",
  "💞": "revolving hearts love",
  "💓": "beating heart love pulse",
  "💗": "growing heart love",
  "💖": "sparkling heart love shine",
  "💝": "heart ribbon gift love",
  "💘": "heart arrow love cupid",
  "💟": "heart decoration love",
  "☮️": "peace symbol sign",
  "✝️": "latin cross christian",
  "☪️": "star crescent islam",
  "🕉️": "om hindu buddhist",
  "☸️": "dharma wheel buddhist",
  "✡️": "star david jewish",
  "🔯": "six pointed star",
  "🕎": "menorah jewish hanukkah",
  "✅": "check mark green done complete yes",
  "❌": "cross mark no wrong delete",
  "❎": "cross mark square no",
  "➕": "plus add",
  "➖": "minus subtract",
  "➗": "divide division",
  "✖️": "multiply times",
  "♾️": "infinity forever endless",
  "❓": "question mark red",
  "❔": "question mark white",
  "❕": "exclamation mark white",
  "❗": "exclamation mark red",
  "💲": "dollar sign money",
  "♻️": "recycling symbol green",
  "🏁": "checkered flag race finish",
  "🚩": "red flag triangular",
  "🎌": "crossed flags japanese",
  "🏴": "black flag",
  "🏳️": "white flag surrender",
  "🏳️‍🌈": "rainbow flag pride lgbtq",
  "🏳️‍⚧️": "transgender flag pride",
  "🏴‍☠️": "pirate flag skull crossbones",
  "🇮🇹": "italy flag italian",
  "🇺🇸": "united states flag usa american",
  "🇬🇧": "united kingdom flag uk british",
  "🇫🇷": "france flag french",
  "🇩🇪": "germany flag german",
  "🇪🇸": "spain flag spanish",
  "🇵🇹": "portugal flag portuguese",
  "🇧🇷": "brazil flag brazilian",
  "🇯🇵": "japan flag japanese",
  "🇰🇷": "south korea flag korean",
  "🇨🇳": "china flag chinese",
  "🇮🇳": "india flag indian",
  "🇷🇺": "russia flag russian",
  "🇦🇺": "australia flag australian",
  "🇨🇦": "canada flag canadian",
  "🇲🇽": "mexico flag mexican",
  "🇦🇷": "argentina flag",
  "🇨🇱": "chile flag",
  "🇨🇴": "colombia flag",
  "🇵🇪": "peru flag",
  "🇻🇪": "venezuela flag",
  "🇪🇨": "ecuador flag",
  "🇧🇴": "bolivia flag",
  "🇺🇾": "uruguay flag",
  "🇵🇾": "paraguay flag",
  "🇹🇷": "turkey flag turkish",
  "🇸🇦": "saudi arabia flag",
  "🇦🇪": "united arab emirates flag uae",
  "🇪🇬": "egypt flag egyptian",
  "🇿🇦": "south africa flag",
  "🇳🇬": "nigeria flag",
  "🇰🇪": "kenya flag",
  "🇬🇭": "ghana flag",
  "🇪🇹": "ethiopia flag",
  "🇲🇦": "morocco flag",
  "🇹🇳": "tunisia flag",
  "🇩🇿": "algeria flag",
  "🇮🇱": "israel flag",
  "🇵🇸": "palestine flag palestinian",
  "🇱🇧": "lebanon flag",
  "🇯🇴": "jordan flag",
  "🇮🇶": "iraq flag",
  "🇮🇷": "iran flag",
  "🇵🇰": "pakistan flag",
  "🇧🇩": "bangladesh flag",
  "🇱🇰": "sri lanka flag",
  "🇳🇵": "nepal flag",
  "🇹🇭": "thailand flag thai",
  "🇻🇳": "vietnam flag vietnamese",
  "🇮🇩": "indonesia flag indonesian",
  "🇲🇾": "malaysia flag",
  "🇵🇭": "philippines flag filipino",
  "🇸🇬": "singapore flag",
  "🇭🇰": "hong kong flag",
  "🇹🇼": "taiwan flag",
  "🇳🇿": "new zealand flag",
  "🇫🇮": "finland flag finnish",
  "🇸🇪": "sweden flag swedish",
  "🇳🇴": "norway flag norwegian",
  "🇩🇰": "denmark flag danish",
  "🇮🇸": "iceland flag",
  "🇳🇱": "netherlands flag dutch",
  "🇧🇪": "belgium flag",
  "🇨🇭": "switzerland flag swiss",
  "🇦🇹": "austria flag",
  "🇵🇱": "poland flag polish",
  "🇨🇿": "czech republic flag",
  "🇭🇺": "hungary flag",
  "🇷🇴": "romania flag",
  "🇧🇬": "bulgaria flag",
  "🇭🇷": "croatia flag",
  "🇷🇸": "serbia flag",
  "🇺🇦": "ukraine flag ukrainian",
  "🇬🇷": "greece flag greek",
  "🇮🇪": "ireland flag irish",
  "🇪🇺": "european union flag eu",
};

export function EmojiPicker({
  onSelect,
  onClose,
  position = "top",
  align = "left",
  className = "",
}: EmojiPickerProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("recent");
  const containerRef = useClickOutside<HTMLDivElement>(onClose);
  const scrollRef = useRef<HTMLDivElement>(null);
  const categoryRefs = useRef<Record<string, HTMLDivElement | null>>({});

  const recentEmojis = useMemo(() => getRecent(), []);

  const categories = useMemo(() => {
    const cats = [...CATEGORIES];
    cats[0] = { ...cats[0], emojis: recentEmojis };
    return cats;
  }, [recentEmojis]);

  const handleSelect = useCallback(
    (emoji: string) => {
      saveRecent(emoji);
      onSelect(emoji);
    },
    [onSelect],
  );

  const filteredCategories = useMemo(() => {
    if (!searchQuery.trim()) return categories;
    const q = searchQuery.toLowerCase();
    return categories
      .map((cat) => ({
        ...cat,
        emojis: cat.emojis.filter(
          (e) => e.includes(q) || EMOJI_KEYWORDS[e]?.toLowerCase().includes(q),
        ),
      }))
      .filter((cat) => cat.emojis.length > 0);
  }, [searchQuery, categories]);

  const scrollToCategory = useCallback((catId: string) => {
    setActiveCategory(catId);
    const el = categoryRefs.current[catId];
    if (el && scrollRef.current) {
      const top = el.offsetTop - scrollRef.current.offsetTop;
      scrollRef.current.scrollTo({ top, behavior: "smooth" });
    }
  }, []);

  // Track active category on scroll
  useEffect(() => {
    const scrollEl = scrollRef.current;
    if (!scrollEl) return;
    const handleScroll = () => {
      const scrollTop = scrollEl.scrollTop + 10;
      let current = categories[0].id;
      for (const cat of categories) {
        const el = categoryRefs.current[cat.id];
        if (el && el.offsetTop - scrollEl.offsetTop <= scrollTop) {
          current = cat.id;
        }
      }
      setActiveCategory(current);
    };
    scrollEl.addEventListener("scroll", handleScroll, { passive: true });
    return () => scrollEl.removeEventListener("scroll", handleScroll);
  }, [categories]);

  const posClass = position === "top" ? "bottom-full mb-3" : "top-full mt-3";
  const alignClass = align === "right" ? "right-0" : "left-0";

  return (
    <div
      ref={containerRef}
      className={`absolute ${posClass} ${alignClass} w-[320px] h-[380px] bg-card border border-border shadow-2xl rounded-xl z-[70] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150 ${className}`}
    >
      {/* Category tabs */}
      <div className="flex items-center gap-0.5 px-2 pt-2 pb-1 border-b border-border/40 shrink-0">
        {categories.map((cat) => {
          const Icon = cat.icon;
          const isActive = activeCategory === cat.id;
          return (
            <button
              key={cat.id}
              className={`w-8 h-8 rounded-lg flex items-center justify-center transition-colors ${
                isActive
                  ? "bg-primary/15 text-primary"
                  : "text-text-secondary hover:text-text-main hover:bg-input/50"
              }`}
              onClick={() => scrollToCategory(cat.id)}
              title={cat.label}
            >
              <Icon className="w-[18px] h-[18px]" />
            </button>
          );
        })}
      </div>

      {/* Search bar */}
      <div className="px-3 py-2 shrink-0">
        <div className="flex items-center gap-2 bg-input/60 border border-border/50 rounded-lg px-3 py-1.5">
          <Search className="w-4 h-4 text-text-secondary shrink-0" />
          <input
            type="text"
            placeholder="Search emoji"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="flex-1 bg-transparent border-none outline-none text-[13px] text-text-main placeholder:text-text-secondary"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery("")}
              className="text-text-secondary hover:text-text-main"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      </div>

      {/* Emoji grid */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-2 pb-2">
        {filteredCategories.map((cat) =>
          cat.emojis.length > 0 ? (
            <div
              key={cat.id}
              ref={(el) => {
                categoryRefs.current[cat.id] = el;
              }}
            >
              <div className="text-[11px] text-text-secondary font-medium px-1 pt-2 pb-1 sticky top-0 bg-card">
                {cat.label}
              </div>
              <div className="grid grid-cols-8 gap-0.5">
                {cat.emojis.map((emoji, i) => (
                  <button
                    key={`${cat.id}-${i}`}
                    className="w-9 h-9 rounded-lg flex items-center justify-center text-[22px] hover:bg-input/60 transition-colors"
                    onClick={() => handleSelect(emoji)}
                  >
                    {emoji}
                  </button>
                ))}
              </div>
            </div>
          ) : null,
        )}
        {filteredCategories.length === 0 && (
          <div className="flex items-center justify-center h-full text-[13px] text-text-secondary">
            No results
          </div>
        )}
      </div>
    </div>
  );
}
